<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.5.1-0-g916b5db  Build Version: 1.5.7152.31018
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="liukuhihna_gazebo">
	
	<xacro:arg name="height" default="0.25" />
  	<xacro:arg name="length"   default="3" />

	<xacro:property name="height" value="$(arg height)" />
	<xacro:property name="length" value="$(arg length)" />

	<xacro:include filename="$(find recon_sim)/urdf/materials.xacro" />

	<link name="world" />

	<joint name="fixed" type="fixed">
		<parent link="world"/>
		<child link="belt_visual"/>
		<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0"/>
	</joint>
	

	<link name="belt_visual">
		<inertial>
			<origin xyz="0 0 ${height}" rpy="0 0 0" />
			<mass value="71.953" />
			<inertia ixx="7.5972" ixy="-1.394E-14" ixz="1.9328E-17" iyy="0.99673" iyz="-9.2056E-18" izz="8.1168" />
		</inertial>
		<visual>
			<origin xyz="0 0 ${height}" rpy="0 0 0" />
			<geometry>
				<box size="0.5 ${length} 0.05"/>
			</geometry>
			<material name="orange"/>
		</visual>
		<collision>
			<origin xyz="0 0 ${height/2}" rpy="0 0 0" />
			<geometry>
				<box size="0.5 ${length} ${height}"/>
			</geometry>
			<!-- <origin xyz="0.0 0.0 0" rpy="1.570796327 0.0 1.570796327"/>
			<geometry>
				<mesh filename="package://demo_world/meshes/conveyor_simple.stl" />
			</geometry> -->
		</collision>
	</link>

	<!-- <link name="test_cube">
		<visual>
			<origin xyz="0.0 0.0 0.37" rpy="0.0 0.0 0.0"/>
			<geometry>
				<box size="0.463 1.2 0.74"/>
			</geometry>
			<material name="purple">
				<color rgba="1 0 1 0.2" />
			</material>
		</visual>
	</link> -->

	<joint name="belt_joint" type="prismatic">
		<origin xyz="0.0 0.0 ${height + 0.025}" rpy="0.0 0.0 0.0"/>
		<parent link="belt_visual"/>
		<child link="belt_moving"/>
		<axis xyz="0 1 0"/>
		<limit lower="0.0" upper="1" effort="1000" velocity="1000"/>
	</joint>

	<link name="belt_moving">
		<inertial>
			<origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
			<mass value="100"/>
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
		</inertial>
		<!-- <visual>
			<origin xyz="0.0 0.0 0.0005" rpy="0.0 0.0 0.0"/>
			<geometry>
				<box size="0.5 5 0.001"/>
			</geometry>
			<material name="test">
				<color rgba="1 0 1 1" />
			</material>
		</visual> -->
		<collision>
			<origin xyz="0.0 0.0 0.0005" rpy="0.0 0.0 0.0"/>
			<geometry>
				<box size="0.5 ${length} 0.001"/>
			</geometry>
		</collision>
	</link>

	<gazebo>
		<plugin name="conveyor_belt_plugin" filename="libROSConveyorBeltPlugin.so">
			<robot_namespace>/</robot_namespace>
			<link>belt_moving</link>
			<power>0</power>
			<max_velocity>1.0</max_velocity>
		</plugin>
	</gazebo>
</robot>
